### ISSUE TITLE
R34 isn't Working

### ISSUE THREAD

**Issue by simvince123** [Fabricio20/LewdWiki#50] opened 2017-08-07 03:16 UTC
When I use the command r34 the bot isn't doing anything

**Comment by Princeperot** [comment] 2017-08-09 00:30
I've been having the same issue. I know that Danbooru's blocked the bot's IP, but it doesn't seem to be pulling anything from Paheal (or whatever other porn sites it uses) either.

**Comment by Fabricio20** [comment] 2017-08-10 17:10
Duplicate of #49

**Closed by Fabricio20** 2017-08-10 17:10 UTC
Labels: Bug, Invalid
